#!/usr/bin/env python3
"""
Interactive setup script for Blocky Market Maker Bot.
Prompts for API credentials on first run and creates .env file.
"""

import os
import sys
import re

ENV_FILE = ".env"

# ANSI colors for terminal output
class Colors:
    HEADER = '\033[95m'
    BLUE = '\033[94m'
    CYAN = '\033[96m'
    GREEN = '\033[92m'
    YELLOW = '\033[93m'
    RED = '\033[91m'
    RESET = '\033[0m'
    BOLD = '\033[1m'


def print_header():
    """Print welcome header."""
    print(f"\n{Colors.CYAN}{Colors.BOLD}")
    print("=" * 50)
    print("  🎮 Blocky Market Maker - Setup Inicial")
    print("=" * 50)
    print(f"{Colors.RESET}\n")


def print_success(message: str):
    """Print success message."""
    print(f"{Colors.GREEN}✅ {message}{Colors.RESET}")


def print_warning(message: str):
    """Print warning message."""
    print(f"{Colors.YELLOW}⚠️  {message}{Colors.RESET}")


def print_error(message: str):
    """Print error message."""
    print(f"{Colors.RED}❌ {message}{Colors.RESET}")


def print_info(message: str):
    """Print info message."""
    print(f"{Colors.BLUE}ℹ️  {message}{Colors.RESET}")


def validate_api_key(api_key: str) -> bool:
    """
    Basic validation for API key format.
    Accepts UUID format or any non-empty string with reasonable length.
    """
    if not api_key or len(api_key) < 8:
        return False
    
    # Check for UUID format (optional, just for better UX)
    uuid_pattern = r'^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
    if re.match(uuid_pattern, api_key):
        return True
    
    # Accept any string with 8+ characters (some APIs use different formats)
    return len(api_key) >= 8


def validate_webhook_url(url: str) -> bool:
    """Basic validation for webhook URL."""
    if not url:
        return True  # Optional field
    
    # Basic URL validation
    return url.startswith("http://") or url.startswith("https://")


def prompt_api_key() -> str:
    """Prompt user for API key."""
    print(f"{Colors.BOLD}Por favor, insira sua API Key da Blocky:{Colors.RESET}")
    print_info("Você pode obter sua API key no painel da Blocky.")
    print()
    
    while True:
        try:
            api_key = input(f"{Colors.CYAN}> {Colors.RESET}").strip()
            
            if not api_key:
                print_error("API Key é obrigatória. Por favor, tente novamente.")
                continue
            
            if not validate_api_key(api_key):
                print_warning("Formato de API key incomum. Tem certeza que está correto? (s/n)")
                confirm = input(f"{Colors.CYAN}> {Colors.RESET}").strip().lower()
                if confirm not in ['s', 'sim', 'y', 'yes']:
                    continue
            
            return api_key
            
        except KeyboardInterrupt:
            print("\n")
            print_warning("Setup cancelado pelo usuário.")
            sys.exit(1)


def prompt_discord_webhook() -> str:
    """Prompt user for Discord webhook URL."""
    print()
    print(f"{Colors.BOLD}Deseja configurar alertas do Discord? (s/n){Colors.RESET}")
    print_info("Alertas enviarão notificações sobre erros e eventos importantes.")
    print()
    
    try:
        choice = input(f"{Colors.CYAN}> {Colors.RESET}").strip().lower()
        
        if choice not in ['s', 'sim', 'y', 'yes']:
            return ""
        
        print()
        print(f"{Colors.BOLD}Insira a URL do Webhook do Discord:{Colors.RESET}")
        print_info("Formato: https://discord.com/api/webhooks/...")
        print()
        
        while True:
            webhook_url = input(f"{Colors.CYAN}> {Colors.RESET}").strip()
            
            if not webhook_url:
                print_info("Webhook não configurado. Você pode adicionar depois no arquivo .env")
                return ""
            
            if not validate_webhook_url(webhook_url):
                print_error("URL inválida. Deve começar com http:// ou https://")
                continue
            
            if "discord.com" not in webhook_url and "discordapp.com" not in webhook_url:
                print_warning("URL não parece ser do Discord. Tem certeza? (s/n)")
                confirm = input(f"{Colors.CYAN}> {Colors.RESET}").strip().lower()
                if confirm not in ['s', 'sim', 'y', 'yes']:
                    continue
            
            return webhook_url
            
    except KeyboardInterrupt:
        print("\n")
        print_info("Webhook não configurado.")
        return ""


def create_env_file(api_key: str, webhook_url: str = ""):
    """Create .env file with provided credentials."""
    content = f"""# Blocky Market Maker Bot - Environment Variables
# Generated by setup.py

# API Configuration (REQUIRED)
BLOCKY_API_KEY={api_key}

# Alert Webhook (OPTIONAL)
# Supported types: discord, slack, telegram, custom
"""
    
    if webhook_url:
        content += f"""ALERT_WEBHOOK_URL={webhook_url}
ALERT_WEBHOOK_TYPE=discord
"""
    else:
        content += """# ALERT_WEBHOOK_URL=
# ALERT_WEBHOOK_TYPE=discord
"""
    
    content += """
# Logging level (DEBUG, INFO, WARNING, ERROR)
# LOG_LEVEL=INFO

# API Endpoint (default: https://craft.blocky.com.br/api/v1)
# BLOCKY_API_ENDPOINT=https://craft.blocky.com.br/api/v1
"""
    
    with open(ENV_FILE, 'w') as f:
        f.write(content)


def check_existing_env() -> bool:
    """Check if .env file already exists."""
    return os.path.exists(ENV_FILE)


def main():
    """Main setup flow."""
    print_header()
    
    # Check if .env already exists
    if check_existing_env():
        print_warning(f"Arquivo {ENV_FILE} já existe!")
        print()
        print("Deseja sobrescrever com uma nova configuração? (s/n)")
        
        try:
            choice = input(f"{Colors.CYAN}> {Colors.RESET}").strip().lower()
            if choice not in ['s', 'sim', 'y', 'yes']:
                print_info("Setup cancelado. Usando configuração existente.")
                return
        except KeyboardInterrupt:
            print("\n")
            print_info("Setup cancelado.")
            return
    
    # Prompt for credentials
    api_key = prompt_api_key()
    webhook_url = prompt_discord_webhook()
    
    # Create .env file
    create_env_file(api_key, webhook_url)
    
    print()
    print_success(f"Configuração salva em {ENV_FILE}")
    print()
    print_info("Para iniciar o bot, execute:")
    print(f"  {Colors.CYAN}python bot.py{Colors.RESET}")
    print()
    print_info("Para modificar configurações avançadas, edite:")
    print(f"  {Colors.CYAN}config.yaml{Colors.RESET}")
    print()


if __name__ == "__main__":
    main()
